### PR TITLE
Use target.cfg.dependencies for platform-specific deps

### PR DESCRIPTION
**Pull request by coolreader18**

### CODE REVIEW

**Review by simnalamburt — APPROVED** [review]

**Review by simnalamburt — CHANGES_REQUESTED** [review]
The directionality of the patch looks good. I'll merge the patch and release the new version if Windows build become successful.

**Comment by coolreader18** [comment]
This push should fix windows.

**Review by simnalamburt — APPROVED** [review]

**Comment by simnalamburt** [comment]
@coolreader18 v0.3.1 published! https://crates.io/crates/utime/0.3.1

**Comment by coolreader18** [comment]
Thanks!

**Comment by simnalamburt** [comment]
Thank you too for turning utime into a project that uses a lighter, more recent dependency.

**Pull request merged**
